service: orgchart-crawler

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  environment:
    SENTRY_DSN: ${env:SENTRY_DSN}
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    SERVICE_DOMAIN: ${env:SERVICE_DOMAIN}
    ORGCHART_CRAWLER_SNS_TOPIC: ${env:ORGCHART_CRAWLER_SNS_TOPIC}
    DOMAIN: ${env:DOMAIN}
  region: eu-central-1
  memorySize: 1024
  timeout: 900
  iam:
    role: arn:aws:iam::889551677573:role/ml_beta_strukturen_bund_dev_lambda_role
  stage: ${opt:stage, "dev"}
  ecr:
    images:
      baseimage:
        path: ./

plugins:
  - serverless-domain-manager
functions:
  app:
    image: baseimage
    events:
      - http:
          method: any
          path: /{proxy+}
      - sns:
          arn: ${env:ORGCHART_CRAWLER_SNS_TOPIC}


custom:
  customDomain:
    autoDomain: true
    domainName: ${env:DOMAIN}
    endpointType: 'regional'
    securityPolicy: tls_1_2
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true